---
title: "README"
output: github_document
date: "2022-11-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Vancouver Trees Shiny App

**For this assignment I have chosen to continue developing my own shiny app**

This repository contains the source code for a shiny app that allows a user to explore the vancouver trees dataset through several interactive features. The features include several variables the users can sort the dataset by, a map that shows the location in the city of the user's selected trees, the ability to colour-code the points on the map for a number of variables, and an interactive and customizable table. 

Some features have also been added to make to app more visually appealing, including the addition of an image as well as changing some theme colours. 
. 

A running instance of the shiny app can be found at:

https://haleymac.shinyapps.io/Assignment_B4/?_ga=2.265606982.879369516.1670034319-171747961.1670034319

The dataset used to create this app is the vancouver_trees dataset, which can be found as part of the 'datateachr' package, or alternatively can be downloaded from https://opendata.vancouver.ca/explore/dataset/street-trees/download/?format=csv&timezone=America/Los_Angeles&lang=en&use_labels_for_header=true&csv_separator=%3B Several modifications to the dataset were made using the dplyr package, and can be found in the beginning of the source code presented in this repository. 

The files in this app include:

app.R - this file contains all of the source code for this application

WWW- this folder contains the image file that was rendered in the app to make it look pretty 
